
version: '3.8'

services:
  ip-tracker:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
